### ISSUE TITLE
Unchecking "Combo track enabled" does not remove the combo tracking window or disable combo tracking

### ISSUE THREAD

**Issue by AntWarden81** [CaiClone/GCDTracker#1]

**Comment by CaiClone** [comment]
Just tested it and seems to be working as expected. Do you also have that window unlocked? moveable windows always show up by default, but I can see how that could be confusing.

**Comment by AntWarden81** [comment]
Window is unlocked. I wasn't sure what the intended functionality of the box was but it didn't seem to do either for me. Lock seems to be the box that hides or unhides the windows for me.

**Comment by CaiClone** [comment]
Yes, it also autohides when out of combat, which together makes it seem like "lock window" is the option that enables it. To disable it you want this:
![image](https://user-images.githubusercontent.com/10381832/146637250-47af595c-75f8-40db-b87a-baff9243ca60.png)
Will do some changes to the settings menu to improve clarity thanks for pointing out how it can be confusing.

I proceed to close the issue. If you still can't get it to behave as you want do not hesitate to reopen.

**Comment by oorzkws** [comment]
> Yes, it also autohides when out of combat, which together makes it seem like "lock window" is the option that enables it. To disable it you want this: ![image](https://user-images.githubusercontent.com/10381832/146637250-47af595c-75f8-40db-b87a-baff9243ca60.png) Will do some changes to the settings menu to improve clarity thanks for pointing out how it can be confusing.
> 
> I proceed to close the issue. If you still can't get it to behave as you want do not hesitate to reopen.

Thanks, I just ran into this.
