### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by aspiringnobody** [CaiClone/GCDTracker#11]
Would it be possible to "unroll" the circular GCD wheel into a width-adjustable castbar?

Thanks, no worries if you don't have time/don't think it's worth it.

**Comment by CaiClone** [comment]
Sure! that sounds like a good idea.
I'm still exposing the configuration options, but is something like this what you are looking for?
(Wheel added just for comparison purposes.)

https://github.com/CaiClone/GCDTracker/assets/10381832/9a0da4f5-b8fc-4a7c-8a2e-dda959f91ae2

**Comment by aspiringnobody** [comment]
> Sure! that sounds like a good idea. I'm still exposing the configuration options, but is something like this what you are looking for? (Wheel added just for comparison purposes.)
> 
>  2024-07-07.13-16-07.mp4

Looks great!  Is it height/width adjustable?  I think I want to occupy the same space as my delvui castbar (for hard casts) and then instant casts will use GCDTracker.  All in the same spot!

**Comment by CaiClone** [comment]
Done!
You should be able to find it in the new v1.0.3.1 that just released. It will be under a new tab called GCDBar that you will have to enable. Yes, you can change the size manually by resizing the windows and you can fine tune it with the width and height ratios if you want some more extreme configurations. Hope it's good and clear.

I'll leave this open for some days in case there is any issue/feedback with the Bar, otherwise enjoy Dawntrail!

**Comment by aspiringnobody** [comment]
Works really well -- the only things I might change would be:

1.  I might like to have an option to show the bar only when the GCD is rolling (as in, not hidden/shown based on combat, but based on if my GCD clock is ticking (aka show only right after I cast a spell).  Maybe stay up for a few moments in "red" mode if I clip afterwards.  This is super low priority, it works great as is.  Just maybe makes it behave more like a regular "castbar"
2.  It might be nice to have a checkbox to disable the part of the red "clipping" that extends past the end of the bar, for cases where there is another UI element placed just to the right of the bar.  I think this represents the animation lock of whatever clipped you extending past the end of the GCD window?  But it's not strictly necessary if the whole bar turns red anyway.

Both of those are super minor suggestions.  I'm totally 120% chuffed with how it is without those changes.

Thanks!

**Comment by aspiringnobody** [comment]
The more I think about it, the more I realize that the clip bleeding past the end of the bar is just a bug.  It makes sense on the circular meter because it "wraps" around by nature of the end of the circle being the same point as the beginning.  But on a bar, the ends are no longer connected, so it just "overflows" into empty space.

I'm not sure if it's better to just clamp the clipped animation lock to the end of the bar, or to try to draw a second rectangle onto the next oGCD.  That's complicated by not knowing if/when another spell will be cast.

**Comment by CaiClone** [comment]
Yeah, that wasn't as hard to implement as I though it would be, definitely looks better when nothing leaves the bar with "Roll GCDs" on.


https://github.com/CaiClone/GCDTracker/assets/10381832/b6d4c37d-ff23-4dec-b38a-af5076a3cab8

Do tell if this is not what you meant.

**Comment by aspiringnobody** [comment]
Looks great.  I'll give it a try tonight to see it in the actual game.

**Comment by CaiClone** [comment]
It's still not released, yet! I am finishing a couple more asks and will release it with 1.0.3.2.

**Comment by aspiringnobody** [comment]
I played for about 4 hours last night.  Seemed to work perfectly.  Thanks a bunch!

**Comment by aspiringnobody** [comment]
Just playing with the only show while GCD is running option.  Love it, that makes it 100% perfect for what I'm using it for.  Thanks so much!

**Comment by aspiringnobody** [comment]
Small bug/issue:  I noticed that the clip'd portion of the bar is actually over the borders:
![clip_borders](https://github.com/user-attachments/assets/23e26905-568a-4142-b42e-13fa6f51eafe)

**Comment by CaiClone** [comment]
Closing this as feature was implemented and conversation about follow up work moved to #13
