### ISSUE TITLE
[Bug] Clip not reset properly after Short Casts

### ISSUE THREAD

**Issue by aspiringnobody** [CaiClone/GCDTracker#20]
To remind us to investigate:

Clipping after a short cast doesn't work properly.  I need to track down the exact problem but for now I'll just say that on my red mage, both the instant cast follow up spell and the hardcast spell that follow the clip are both red background, and then after the hardcast spell completes the background goes back to the default.  

I think we need to track clippedGCD on this GCD and clippedGCD on last GCD like we do with the ABC alert to fix this, but I haven't really investigated why it's happening yet so that's just my gut feeling.  Opening this to remind myself to fix this once my PR for the text bug is merged and I can work in my main again.

Feel free to fix if you've got an easy way off the top of your head, if not assign to me and I'll figure it out.

**Comment by CaiClone** [comment]
I'm not able to replicate, so it may be settings/inconsistent, just to make sure, what I'm trying is:
```
GCD 1: Enchanted Riposte -> Swiftcast (clipping)
(Alert and bar goes red)
GCD 2: swift Verthunder
(bar resets to white)
```
and
```
GCD 1: Enchanted Riposte -> Fleche (clipping)
(Alert and bar goes red)
GCD 2: Hardcast Verthunder
(bar resets to white)
```
Is that the same sequence that's failing you?

**Comment by aspiringnobody** [comment]
Try clipping jolt instead.

**Comment by aspiringnobody** [comment]
Specifically:

Jolt -> (clip with Flèche) -> Jolt -> Jolt

I’ll do more testing later but if it only happens with Jolt repeated it’s probably related to the bug I noticed a long time ago where using the same oGCD twice registers as abc instead of clipping.

**Comment by aspiringnobody** [comment]
I've got this fixed now, I think.  See https://github.com/CaiClone/GCDTracker/pull/21

**Comment by CaiClone** [comment]
Yes, I did get the same issue after clipping the casted Jolt. And #21 did fix it, thank you!
I'm rewriting a little the interface so we can fake this kind of edge cases in testing, that way we could add this and others as edge cases and ensure they always keep working.
