### ISSUE TITLE
[Request] Maintain clipping overlay for duration of next GCD

### ISSUE THREAD

**Issue by oorzkws** [CaiClone/GCDTracker#4]
As it is currently, if you clip late in the GCD you may not see it - the red portion will disappear as soon as the GCD rolls over. My suggestion would be to retain the clipping portion of the overlay until the wheel reaches that point again, or until the next instance of clipping, whichever happens sooner.

**Comment by CaiClone** [comment]
I agree with this, it worked that way in a previous iteration, but I felt like it made the already cluttered wheel worse, and it got confusing when the clipped portion had to change size with cooldowns that speed up the GCD (MCH or DNC).

I was toying with the idea of displaying the clipped ms as a toast for a couple of seconds, see example here:
![exampleToast](https://user-images.githubusercontent.com/10381832/149673062-1058694a-aad0-4170-b6c9-107b2cbe3191.png)
Would that work? would appreciate ideas on how to make it better.

**Comment by oorzkws** [comment]
That's a good point with the GCD changing duration, I hadn't considered that. I think a binary indicator would work better in my opinion, there's enough going on that a yes/no (or a yes/blank) would be preferable to something more to read.

**Comment by CaiClone** [comment]
You are right, might be too much information, I'm working with this right for now, because I can't think about a neater way that's easy to understand.
![ClipNotice](https://user-images.githubusercontent.com/10381832/150030337-3d26b41c-fff9-42ca-8b03-097a79d33dfc.gif)
Obviously would have some setting to turn it off when it gets annoying.

**Comment by oorzkws** [comment]
I'm a bit torn, as that's more noticeable but I feel like the window isn't much longer than how long the red shows on the bar. Maybe making the slim bar's background red for the clipped GCD?

**Comment by CaiClone** [comment]
Yep, that looks a lot better:
![ClipNotice](https://user-images.githubusercontent.com/10381832/151267046-85c697b8-5795-49de-b3ef-aed12bf55267.gif)
I'll polish it a bit, add some config options and it will be in the next release.

**Comment by oorzkws** [comment]
Thanks! I'm looking forward to giving it a shot
