### ISSUE TITLE
Color changes aren't retained after game restart

### ISSUE THREAD

**Issue by asherdunn** [CaiClone/GCDTracker#5]
Changes to, for example, GCD bar color, are reverted to default after restarting FFXIV.

**Comment by CaiClone** [comment]
Hello, thanks for the report!

I'm having some trouble replicating this issue, either with old config files or new instances. Could you provide some more information, which color are you selecting? Are you on version 1.0.2.1?

Also, you might want to take a look at deleting/renaming the "GCDTracker.json" file at %appdata%\XIVLauncher\pluginConfigs. If it's an invalid config issue that should fix the issue.

**Comment by CaiClone** [comment]
Closing this due to not being able to replicate, If the issue persists feel free to reopen.
