### ISSUE TITLE
Is it anywhere I can obtain older API plugin?

### ISSUE THREAD

**Issue by takaqiao** [CaiClone/GCDTracker#7]
Tried to search older commits but cant find any older version of GCDTracker:) Trying to find last API5 GCDTracker for cn client

**Comment by CaiClone** [comment]
Hello.

I have uploaded a [release](https://github.com/CaiClone/GCDTracker/releases/tag/v1.0.2.0) with the zip file of the latest API 5 version, does that work?
I was unaware of clients using older versions. I'll keep posting the last version for each API on the releases, but if there's a more standard way to support older clients used by other plugins please do mention it here!
