### ISSUE TITLE
Update for 6.2

### ISSUE THREAD

**Issue by wirchtalksgames** [CaiClone/GCDTracker#8]
Hi! I'm not sure if you're still active in the scene, but this plugin has been very useful to me, and I miss having it installed. Is there a chance this will be getting an update for the current version of the game/Dalamud? Thanks!

**Comment by CaiClone** [comment]
Yep! Just updated it API7 now.
Thank you for pinging me, I hadn't realized this got outdated.

**Comment by wirchtalksgames** [comment]
Thanks, you're the best!
