### ISSUE TITLE
Always "clipping" after noclippy update

### ISSUE THREAD

**Issue by oorzkws** [CaiClone/GCDTracker#9]
Hi,

With the most recent version of noclippy, any double weaves show as a clip even with 2.50gcd. They aren't actually clipping as far as I can tell, there's no execution delay like with regular clipping.

Noclippy repo for dalamud: https://raw.githubusercontent.com/UnknownX7/DalamudPluginRepo/master/pluginmaster.json

**Comment by CaiClone** [comment]
Thank you for noticing!
I updated the code to account for the new animationLock set by NoClippy, so it should work well with version v1.0.2.4. Do tell me if you still see weird issues with it.

**Comment by oorzkws** [comment]
Cheers, thanks. I'll report back when I have a chance to test it out.

**Comment by oorzkws** [comment]
Confirmed resolved, thanks for waiting for me to raidlog 😄
